// <auto-generated />
using Dragon.Business.Data;
using Dragon.Business.Data.CompiledModels;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppDbContext), typeof(AppDbContextModel))]
