// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Dragon.Business.Data.CompiledModels
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("ae709170-5513-4458-9a35-6c32b274983e"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var payment = PaymentEntityType.Create(this);
            var staffMember = StaffMemberEntityType.Create(this);
            var transaction = TransactionEntityType.Create(this);

            PaymentEntityType.CreateAnnotations(payment);
            StaffMemberEntityType.CreateAnnotations(staffMember);
            TransactionEntityType.CreateAnnotations(transaction);

            AddAnnotation("ProductVersion", "9.0.0");
        }
    }
}
